version: '3'
services:

  go-web:
    build:
      context: .
      dockerfile: dockerfile
      args:
        buildno: 1
    # command: ./app
    restart: always
    # ports:
    #   - "8080:8080"
    # expose:
    #   - 8080
    networks:
      - web_web
    volumes:
      - /etc/code/conf/go-web/config.json:/root/code/config.json
      - /etc/code/logs/go-web:/root/code/log
    container_name: go-web
