FROM golang:1.20.4-alpine as builder
ENV GO111MODULE=auto \
    # GOPROXY=https://goproxy.cn,direct \
    CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64
COPY . /root/code/
WORKDIR /root/code
RUN go build -o app ./main

FROM alpine:3.18 as prod
WORKDIR /root/
# COPY --from=0 /root/code/app .
COPY --from=builder /root/code/app .
EXPOSE 8080
CMD ["./app"]